version: '3.8'

services:
  ros_turtlesim_vnc:
    build: .
    ports:
      - "5901:5901"
      - "6080:6080"
    volumes:
      - ./src:/home/ros/ros_workspace/src
    environment:
      - DISPLAY=:1
      - ROS_DOMAIN_ID=0
